Import all libraries to format datasets

In [72]:
import pandas as pd
import os

Here is defined columns with actual data and indexes

In [26]:
cols = ['2010', '2011', '2012', '2013', '2014','2015','2016','2017']
indeces = ['2010i', '2011i', '2012i', '2013i', '2014i', '2015i', '2016i']

Function for indeces calculation

In [100]:
def calc_indeces(df):
    for i in range(len(indeces)):
        df[indeces[i]] = round(((df[cols[i + 1]] / df[cols[i]]) - 1) * 100, 2)
    df = df[['TIME']+indeces]
    return df

Function for transforming table into dataset with indeces

In [97]:
def format_dataset(path):
    df = pd.read_csv(path+'/prepared.csv')
    df = calc_indeces(df)
    df.to_csv(path+'/formatted.csv',index=False)

Here is defined all paths with prepared tables

In [105]:
tables = [x[0] for x in os.walk('data')]
##removing data folder from list
tables.pop(0)

'data'

Applying formatting and indeces calculation for all tables in folder table

In [104]:
for table in tables:
    format_dataset(table)

Example of formatted output

In [106]:
pd.read_csv('data/house_price_index/formatted.csv')

,TIME,2010i,2011i,2012i,2013i,2014i,2015i,2016i
0,Belgium,4.01,2.24,1.18,-0.56,1.68,2.64,3.63
1,Bulgaria,-5.51,-1.91,-2.19,1.43,2.79,7.02,8.67
2,Czechia,0.11,-1.47,0.00,2.45,3.95,7.20,11.66
3,Denmark,-1.70,-2.70,3.90,3.77,6.96,5.22,4.54
4,Germany (until 1990 former territory of the FRG),3.46,3.46,3.12,3.13,4.71,7.50,6.14
5,Estonia,8.48,7.29,10.65,13.72,6.86,4.75,5.50
6,Ireland,-17.08,-13.45,1.25,16.53,11.46,7.46,10.91
7,Spain,-7.64,-14.78,-9.12,0.31,3.58,4.62,6.19
8,France,5.81,-0.55,-1.90,-1.59,-1.47,1.01,3.12
9,Croatia,0.17,-1.56,-3.95,-1.58,-2.89,0.89,3.83
10,Italy,1.35,-2.51,-6.51,-4.67,-3.85,0.30,-1.10
11,Cyprus,-1.60,-3.05,-4.09,-1.76,-1.45,0.27,2.24
12,Latvia,10.43,2.96,6.85,6.00,-3.36,8.49,8.78
13,Lithuania,6.62,-0.23,1.22,6.42,3.66,5.40,8.92
14,Luxembourg,3.68,4.20,4.98,4.39,5.40,6.01,5.61
15,Hungary,-3.43,-3.70,-2.56,4.19,13.08,13.38,12.22
16,Malta,-1.36,3.05,-0.41,2.55,5.81,5.45,5.29
17,Netherlands,-1.98,-6.71,-6.00,0.81,3.59,5.02,7.53
18,Austria,6.25,7.32,5.17,3.51,4.90,8.53,5.28
19,Poland,0.09,-3.49,-4.38,0.98,1.52,1.86,3.85
20,Portugal,-4.91,-7.07,-1.88,4.24,3.05,7.12,9.24
21,Romania,-12.31,-5.07,-0.25,-2.06,2.86,5.95,6.05
22,Slovenia,2.71,-6.89,-5.25,-6.60,0.81,3.25,8.27
23,Slovakia,-1.50,-2.71,0.91,1.41,5.36,6.70,5.90
24,Finland,3.18,2.42,1.15,-0.35,0.00,0.81,1.56
25,Sweden,2.57,1.27,5.15,9.42,13.12,8.24,6.64
26,United Kingdom,-1.47,0.38,2.57,8.02,5.93,6.99,4.55
27,Iceland,4.64,6.91,5.76,8.43,8.24,9.77,19.52
28,Norway,8.16,6.75,4.30,2.74,6.68,7.88,5.44
29,Turkey,6.94,9.48,11.41,13.62,16.13,13.27,10.21